
# API
# -----------------------------------
# User
create-user:
    path: '/api/account/create'
    controller: App\Controller\UserController::createAccount
    methods: POST
user-edit:
    path: '/api/user/{id}/edit'
    controller: App\Controller\UserController::editUser
    methods: PATCH
user-areas:
    path: '/api/user/areas'
    controller: App\Controller\UserController::getUserAreas
    methods: GET
user-pages:
    path: '/api/user/pages'
    controller: App\Controller\UserController::getUserPages
    methods: GET
user-features:
    path: '/api/user/features'
    controller: App\Controller\UserController::getUserFeatures
    methods: GET
user-specs:
    path: '/api/user/specs'
    controller: App\Controller\UserController::getUserSpecs
    methods: GET
user-details:
    path: '/api/user/{id}'
    controller: App\Controller\UserController::getUserDetails
    methods: GET

#Area
create-area:
    path: '/api/area/create'
    controller: App\Controller\AreaController::createArea
    methods: POST
area-edit:
    path: '/api/area/{id}/edit'
    controller: App\Controller\AreaController::editArea
    methods: PATCH
area-details:
    path: '/api/area/{uid}'
    controller: App\Controller\AreaController::getAreaDetails
    methods: GET

# Project
create-core:
    path: '/api/project/create-core'
    controller: App\Controller\ProjectController::createCore
    methods: POST
create-project:
    path: '/api/project/create-project'
    controller: App\Controller\ProjectController::createProject
    methods: POST
update-status:
    path: '/api/project/update-status'
    controller: App\Controller\ProjectController::updateStatus
    methods: POST
update-section:
    path: '/api/project/update-section'
    controller: App\Controller\ProjectController::updateSection
    methods: POST
update-project:
    path: '/api/project/update'
    controller: App\Controller\ProjectController::updateProject
    methods: POST
projects-get-all:
    path: '/api/projects/get-all'
    controller: App\Controller\ProjectController::getAll
    methods: GET
project-info:
    path: '/api/project/{uid}'
    controller: App\Controller\ProjectController::getProjectInfo
    methods: GET

# Element
element-create:
    path: '/api/element/create'
    controller: App\Controller\ElementController::createElement
    methods: POST
element-edit:
    path: '/api/element/{id}/edit'
    controller: App\Controller\ElementController::editElement
    methods: PATCH
element-details:
    path: '/api/element/{uid}'
    controller: App\Controller\ElementController::getElementDetails
    methods: GET

# Connection
connection-create:
    path: '/api/connection/create'
    controller: App\Controller\ConnectionController::createConnection
    methods: POST
connection-edit:
    path: '/api/connection/{id}/edit'
    controller: App\Controller\ConnectionController::editConnection
    methods: PATCH
connection-delete:
    path: '/api/connection/{id}/delete'
    controller: App\Controller\ConnectionController::deleteConnection
    methods: DELETE
connection-details:
    path: '/api/connection/{uid}'
    controller: App\Controller\ConnectionController::getConnectionDetails
    methods: GET

# Page
page-create:
    path: '/api/page/create'
    controller: App\Controller\PageController::createPage
    methods: POST
page-edit:
    path: '/api/page/{id}/edit'
    controller: App\Controller\PageController::editPage
    methods: PATCH
page-delete:
    path: '/api/page/{id}/delete'
    controller: App\Controller\PageController::deletePage
    methods: DELETE
page-details:
    path: '/api/page/{uid}'
    controller: App\Controller\PageController::getPageDetails
    methods: GET

# Feature
feature-create:
    path: '/api/feature/create'
    controller: App\Controller\FeatureController::createFeature
    methods: POST
feature-edit:
    path: '/api/feature/{id}/edit'
    controller: App\Controller\FeatureController::editFeature
    methods: PATCH
feature-delete:
    path: '/api/feature/{id}/delete'
    controller: App\Controller\FeatureController::deleteFeature
    methods: DELETE
feature-info:
    path: '/api/feature/{uid}'
    controller: App\Controller\FeatureController::getFeatureDetails
    methods: GET

# Spec
spec-create:
    path: '/api/spec/create'
    controller: App\Controller\SpecController::createSpec
    methods: POST
spec-edit:
    path: '/api/spec/{id}/edit'
    controller: App\Controller\SpecController::editSpec
    methods: PATCH
spec-delete:
    path: '/api/spec/{id}/delete'
    controller: App\Controller\SpecController::deleteSpec
    methods: DELETE
spec-info:
    path: '/api/spec/{uid}'
    controller: App\Controller\SpecController::getSpecDetails
    methods: GET

# Validation
validation-create:
    path: '/api/validation/add'
    controller: App\Controller\ValidationController::addValidation
    methods: POST
validation-delete:
    path: '/api/validation/remove'
    controller: App\Controller\ValidationController::removeValidation
    methods: POST

# Invitation
invitation-create:
    path: '/api/invitation/create'
    controller: App\Controller\InvitationController::createInvitation
    methods: POST
invitation-details:
    path: '/api/invitation/{uid}'
    controller: App\Controller\InvitationController::getInvitationDetails
    methods: GET

# Feedback
feedback-create:
    path: '/api/feedback/create'
    controller: App\Controller\FeedbackController::createFeedback
    methods: POST
feedback-edit:
    path: '/api/feedback/{id}/edit'
    controller: App\Controller\FeedbackController::editFeedback
    methods: PATCH
# Security
login:
    path: '/api/login'
    controller: App\Controller\SecurityController::login
    methods: POST

# Default
default1:
    path: '/api'
    controller: App\Controller\DefaultController::default
    methods: GET
default2:
    path: '/api/{path}'
    controller: App\Controller\DefaultController::default
    methods: GET
default3:
    path: '/api/{path}/{slug}'
    controller: App\Controller\DefaultController::default
    methods: GET
default4:
    path: '/api/{path}/{slug}/{id}'
    controller: App\Controller\DefaultController::default
    methods: GET

# APP
# -----------------------------------
# App front
app_landing:
    path: /
    controller: App\Controller\AppController
app:
    path: '/{path}'
    controller: App\Controller\AppController
app2:
    path: '/{path}/{slug}'
    controller: App\Controller\AppController
app3:
    path: '/{path}/{slug}/{id}'
    controller: App\Controller\AppController